# Generated by Django 4.1.4 on 2023-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0003_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
