# Generated by Django 4.1.4 on 2023-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_meep_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meep',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
